- id: doi:10.1109/jstsp.2022.3214774
  image: https://github.com/NicoDeshler/I2SL-Website/blob/main/images/citations/constellation_personick.JPG
  tags:
    - superresolution
    - bayesian inference
